type User {
  id: ID!
  name: String
  email: String!
  pwd: String!
}

input CreateUser {
  name: String
  email: String!
  pwd: String!
  test: String
}

input ConfirmCreateUser {
  name: String
  email: String!
  pwd: String!
  code: Int!
}

type Query {
  codeEmail(input: CreateUser!): Boolean!
  verifyCode(input: ConfirmCreateUser!): Boolean!
}

type Mutation {
  createUser(input: CreateUser!): User
  deleteUser(): User
}