type User {
  _id: ID!
  name: String
  email: String!
  pwd: String!
}

type ReturnUser {
  _id: ID!
  name: String
  email: String!
}

input CreateUser {
  name: String
  email: String!
  pwd: String!
  test: String
}

input ConfirmCreateUser {
  name: String
  email: String!
  pwd: String!
  code: Int!
}

type Query {
  codeEmail(input: CreateUser!): Boolean!
  verifyCode(input: ConfirmCreateUser!): Boolean!
  logIn(input: CreateUser): Boolean!
  logOut: Boolean!
}

type Mutation {
  createUser(input: CreateUser!): ReturnUser
  deleteUser: ReturnUser
}